// prettier-ignore
// eslint-disable
// AUTOGENERATED!!! Do not change
import { parse } from "generate-content-spreadsheet/parse";

/**
 * Content from spreadsheet 1RXjhi32S2zIfFivybqL95tKybpN66z-d7skajXJ1jsM tab Strings
 * @link https://docs.google.com/spreadsheets/d/1RXjhi32S2zIfFivybqL95tKybpN66z-d7skajXJ1jsM/edit
 */
export let Strings = {
  title: "My title",
  root: {
    title: "My index page title",
    description: ["My index page description 1", "My index page description 2"],
  },
} as const;

type StringsType = typeof Strings;

/**
 * Update Strings.
 * Will fetch new strings and update Strings in-place
 */
export const update = async () => {
  try {
    const data = await parse(
      undefined,
      undefined,
      undefined,
      "1RXjhi32S2zIfFivybqL95tKybpN66z-d7skajXJ1jsM",
      "Strings",
      undefined
    );
    const updated = data as unknown as StringsType;
    Strings = updated;
    return updated;
  } catch (e) {
    console.warn("Failed to update", e);
    return Strings;
  }
};
